os: linux
dist: xenial

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "osnl20"
#    token: $SONAR_TOKEN

script:
  - qmake
  - make
  - ls tests -a
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - ls tests -a
  - ./tests/tests

after_success:
  - pwd
  - ls -a
  - ls app -a
  - ls tests -a
  - coveralls --root . -i "app/" -e "externals/" -e "bw-output/" --verbose
  - ls app -a
  - ls tests -a
  - sonar-scanner

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
